[package]
name = "ratatui-diff"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = { version = "0.20.2" }
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
unicode-width = { version = "0.2.0" }
